import { ethers } from "ethers";
import { ZkSyncProvider } from "ethers-v6-zksync-compat";
export declare function signBundle(signer: any, body: any): Promise<string>;
export declare function providerFromChainId(chainId: any): ethers.InfuraProvider | ZkSyncProvider;
export declare function toProvider(p: any): any;
export declare const logger: any;
export declare function walletFromEnv(): ethers.Wallet | ethers.HDNodeWallet;
export declare function providerFromEnv(): ethers.InfuraProvider | ZkSyncProvider;
export declare const PINTSWAP_DIRECTORY: string;
export declare const PINTSWAP_PEERID_FILEPATH: string;
export declare function expandValues([token, amount, tokenId]: [any, any, any], provider: any): Promise<any[]>;
export declare function expandOffer(offer: any, provider: any): Promise<{
    givesToken: any;
    givesAmount: any;
    givesTokenId: any;
    getsToken: any;
    getsAmount: any;
    getsTokenId: any;
}>;
export declare const PINTSWAP_DATA_FILEPATH: string;
